import type { SafetyIncident, Auditor, Area, RiskType } from './types';

export const auditors: Auditor[] = [
  { id: '1', name: 'Anderson José Silva' },
  { id: '2', name: 'Jackson Ribeiro' },
  { id: '3', name: 'Ozivan Torres' },
  { id: '4', name: 'Ana Lucia' },
  { id: '5', name: 'Diego Nogueira' },
  { id: '6', name: 'Gerson Junior' },
  { id: '7', name: 'Dieison Teixeira' },
];

export const areas: Area[] = [
    { id: '1', name: 'GTP' },
    { id: '2', name: 'Sinterização' },
    { id: '3', name: 'Lingotamento' },
    { id: '4', name: 'Aciaria' },
    { id: '5', name: 'Pátio' },
    { id: '6', name: 'Ponte Rolante' },
    { id: '7', name: 'NR 12' },
    { id: '8', name: 'Energia' },
    { id: '9', name: 'Coqueria' },
    { id: '10', name: 'Alto Forno' },
];

export const riskTypes: RiskType[] = [
    { id: '1', name: 'Isolamento Deficiente' },
    { id: '2', name: 'Piso Irregular' },
    { id: '3', name: 'Cinto de Segurança Avariado' },
    { id: '4', name: 'Documentação' },
    { id: '5', name: 'Outros:' },
    { id: '6', name: 'Ausência de FISPQ' },
    { id: '7', name: 'Colaborador sem EPI' },
    { id: '8', name: 'Extintor' },
    { id: '9', name: 'Acesso' },
    { id: '10', name: 'Risco de choque elétrico' },
    { id: '11', name: 'Atropelamento' },
    { id: '12', name: 'Isolamento Caído' },
    { id: '13', name: 'Falta de Isolamento' },
];

export const incidents: SafetyIncident[] = [
  {
    id: '1',
    timestamp: '5/27/2025 14:21:50',
    area: 'Lingotamento',
    auditor: 'Anderson José Silva',
    date: '2025-05-27',
    riskType: 'Isolamento Deficiente',
    potential: 'Baixo',
    description: 'Isolamento inadequado próximo ao prédio novo do lingotamento.',
    correctiveAction: 'O mesmo foi corrigido de forma q evite a entrada de pessoas não autorizadas.',
    responsible: 'Equipe de Manutenção',
    deadline: '2025-05-27',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '2',
    timestamp: '5/28/2025 15:03:53',
    area: 'Aciaria',
    auditor: 'Jackson Ribeiro',
    date: '2025-05-28',
    riskType: 'Piso Irregular',
    potential: 'Alto',
    description: 'Rodapé do andaime com risco de qued',
    correctiveAction: 'Foi pedido o apóio do pessoal do andaime ( contrex) o mesmo foi corrigido na mesma hora',
    responsible: 'Contrex',
    deadline: '2025-05-28',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '3',
    timestamp: '5/30/2025 13:21:58',
    area: 'GTP',
    auditor: 'Ozivan Torres',
    date: '2025-05-30',
    riskType: 'Cinto de Segurança Avariado',
    potential: 'Sem Desvio',
    description: 'Foi verificado o equipamento do colaborador e não estava com avarias,foi vericado check list e documentação estavam com preenchimento correto',
    correctiveAction: 'Satisfatória',
    responsible: 'Ozivan Torres',
    deadline: '2025-05-30',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '4',
    timestamp: '5/30/2025 13:53:53',
    area: 'Sinterização',
    auditor: 'Ana Lucia',
    date: '2025-05-27',
    riskType: 'Documentação',
    potential: 'Médio',
    description: 'Documentação da equipe estava incompleta , sem ponto de encontro , sem assinatura do responsável pela execução , sem o horário de início e fechamento',
    correctiveAction: 'Documentação foi regularizada.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-27',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '5',
    timestamp: '5/30/2025 13:57:30',
    area: 'Sinterização',
    auditor: 'Ana Lucia',
    date: '2025-05-27',
    riskType: 'Outros:',
    potential: 'Médio',
    description: 'Colaborador usando isqueiro normal para acender maçarico',
    correctiveAction: 'Colaborador orientado a usar acendedor apropriado.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-27',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '6',
    timestamp: '5/30/2025 13:59:21',
    area: 'GTP',
    auditor: 'Ana Lucia',
    date: '2025-05-27',
    riskType: 'Documentação',
    potential: 'Médio',
    description: 'Documentação estava incompleta , sem ponto de encontro e marcação no campo de projeção estava errado',
    correctiveAction: 'Documentação foi corrigida.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-27',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '7',
    timestamp: '5/30/2025 14:00:39',
    area: 'GTP',
    auditor: 'Ana Lucia',
    date: '2025-05-27',
    riskType: 'Ausência de FISPQ',
    potential: 'Médio',
    description: 'Colaboradores estavam sem a FDS do produto que estavam utilizando na atividade',
    correctiveAction: 'FDS (FISPQ) foi providenciada e disponibilizada.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-27',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '8',
    timestamp: '5/30/2025 14:04:30',
    area: 'Pátio de Matéria Prima',
    auditor: 'Ana Lucia',
    date: '2025-05-28',
    riskType: 'Colaborador sem EPI',
    potential: 'Médio',
    description: 'Colaborador soldando sem óculos e máscara facial',
    correctiveAction: 'Atividade interrompida e colaborador orientado sobre a obrigatoriedade do uso de EPI.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-28',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '9',
    timestamp: '5/30/2025 14:08:17',
    area: 'Pátio de Matéria Prima',
    auditor: 'Ana Lucia',
    date: '2025-05-28',
    riskType: 'Extintor',
    potential: 'Médio',
    description: 'Etiqueta de extintores estava faltando inspeção mensal de mês de maio',
    correctiveAction: 'Inspeção foi realizada e etiqueta atualizada.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-28',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '10',
    timestamp: '5/30/2025 14:09:08',
    area: 'Alto Forno',
    auditor: 'Diego Nogueira',
    date: '2025-05-30',
    riskType: 'Acesso',
    potential: 'Baixo',
    description: 'O banheiro masculino o piso se encontra afundando canteiro central Vitória industrial.',
    correctiveAction: 'Equipe de manutenção foi acionada para reparo.',
    responsible: 'Diego nogueira da costa',
    deadline: '2025-05-30',
    status: 'Em Andamento',
    photos: [],
  },
  {
    id: '11',
    timestamp: '5/30/2025 14:09:56',
    area: 'Lingotamento',
    auditor: 'Ana Lucia',
    date: '2025-05-29',
    riskType: 'Colaborador sem EPI',
    potential: 'Médio',
    description: 'Colaboradores estavam na área sem o protetor auricular e não estavam usando o óculos',
    correctiveAction: 'Colaboradores foram orientados e passaram a utilizar os EPIs corretamente.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-29',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '12',
    timestamp: '6/2/2025 7:36:47',
    area: 'Sinterização',
    auditor: 'Ana Lucia',
    date: '2025-05-31',
    riskType: 'Documentação',
    potential: 'Médio',
    description: 'Documentação(APR) da equipe estava com as assinaturas de responsável pelo serviço e responsável pela execução da tarefa trocadas , e a PT ar quente estava sem horários de início e término e sem o nome da empresa',
    correctiveAction: 'Documentação foi corrigida e preenchida corretamente.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-31',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '13',
    timestamp: '6/2/2025 7:41:11',
    area: 'Sinterização',
    auditor: 'Ana Lucia',
    date: '2025-05-31',
    riskType: 'Documentação',
    potential: 'Médio',
    description: 'Colaboradores estava usando uma APR com a logo de outra empresa',
    correctiveAction: 'APR foi substituída pelo documento correto.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-31',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '14',
    timestamp: '6/2/2025 7:42:50',
    area: 'Sinterização',
    auditor: 'Ana Lucia',
    date: '2025-05-31',
    riskType: 'Colaborador sem EPI',
    potential: 'Médio',
    description: 'Colaborador estava na área sem óculos ampla visão',
    correctiveAction: 'Colaborador foi orientado e passou a utilizar o EPI.',
    responsible: 'Ana Lucia',
    deadline: '2025-05-31',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '15',
    timestamp: '6/2/2025 10:47:36',
    area: 'Ponte Rolante',
    auditor: 'Gerson Junior',
    date: '2025-06-02',
    riskType: 'Risco de choque elétrico',
    potential: 'Alto',
    description: 'Cabos elétricos pendurados em estrutura metálica.',
    correctiveAction: 'Cabos foram removidos e realocados de forma segura.',
    responsible: 'Gerson Marcena',
    deadline: '2025-06-02',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '16',
    timestamp: '6/2/2025 11:41:53',
    area: 'Lingotamento',
    auditor: 'Dieison Teixeira',
    date: '2025-06-02',
    riskType: 'Outros:',
    potential: 'Médio',
    description: 'Operador da ponte rolante parou a cabine em cima do caminho seguro e a mangueira doa ar condicionado ficou jogando água no acesso seguro podendo ocasionar queda de mesmo nível',
    correctiveAction: 'Comuniquei o operador da ponte rolante e ele deslocou a mesma',
    responsible: 'Operador da Ponte',
    deadline: '2025-06-02',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '17',
    timestamp: '6/2/2025 11:43:51',
    area: 'Lingotamento',
    auditor: 'Dieison Teixeira',
    date: '2025-05-29',
    riskType: 'Atropelamento',
    potential: 'Alto',
    description: 'Colaborador estava iniciando a travessia fora da faixa de pedestre',
    correctiveAction: 'Colaborador foi orientado a atravessar na faixa de pedestre',
    responsible: 'Colaborador',
    deadline: '2025-05-29',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '18',
    timestamp: '6/2/2025 11:47:01',
    area: 'Lingotamento',
    auditor: 'Dieison Teixeira',
    date: '2025-05-29',
    riskType: 'Isolamento Caído',
    potential: 'Alto',
    description: 'O isolamento que estava isolando a área demarcada do maquinário atuar estava caído e um pouco curto para a proporção da atividade',
    correctiveAction: 'Orientei ao sinaleiro responsável para ajeitar o isolamento',
    responsible: 'Sinaleiro',
    deadline: '2025-05-29',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '19',
    timestamp: '6/2/2025 14:06:30',
    area: 'Lingotamento',
    auditor: 'Dieison Teixeira',
    date: '2025-06-02',
    riskType: 'Falta de Isolamento',
    potential: 'Baixo',
    description: 'Material com falta de isolamento ao seu derredor',
    correctiveAction: 'Foi feito o isolamento e comunicado aos responsáveis',
    responsible: 'Equipe de Isolamento',
    deadline: '2025-06-02',
    status: 'Resolvido',
    photos: [],
  },
  {
    id: '20',
    timestamp: '6/3/2025 21:41:27',
    area: 'Aciaria',
    auditor: 'Gerson Junior',
    date: '2025-06-03',
    riskType: 'Outros:',
    potential: 'Alto',
    description: 'Durante o almoço foi encontrado um pedaço de vidro no prato do colaborador.',
    correctiveAction: 'Refeição foi substituída e a cozinha notificada para investigar a origem.',
    responsible: 'Gerson Marcena',
    deadline: '2025-06-03',
    status: 'Resolvido',
    photos: [],
  },
];